##########################################################################################################################
# File automatically-generated by STM32forVSCode
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = indoor-bike-computer


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Og


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
C_SOURCES =  \
Core/Lib/LVGL/src/core/lv_group.c \
Core/Lib/LVGL/src/core/lv_obj.c \
Core/Lib/LVGL/src/core/lv_obj_class.c \
Core/Lib/LVGL/src/core/lv_obj_draw.c \
Core/Lib/LVGL/src/core/lv_obj_event.c \
Core/Lib/LVGL/src/core/lv_obj_id_builtin.c \
Core/Lib/LVGL/src/core/lv_obj_pos.c \
Core/Lib/LVGL/src/core/lv_obj_property.c \
Core/Lib/LVGL/src/core/lv_obj_scroll.c \
Core/Lib/LVGL/src/core/lv_obj_style.c \
Core/Lib/LVGL/src/core/lv_obj_style_gen.c \
Core/Lib/LVGL/src/core/lv_obj_tree.c \
Core/Lib/LVGL/src/core/lv_refr.c \
Core/Lib/LVGL/src/display/lv_display.c \
Core/Lib/LVGL/src/draw/lv_draw.c \
Core/Lib/LVGL/src/draw/lv_draw_arc.c \
Core/Lib/LVGL/src/draw/lv_draw_buf.c \
Core/Lib/LVGL/src/draw/lv_draw_image.c \
Core/Lib/LVGL/src/draw/lv_draw_label.c \
Core/Lib/LVGL/src/draw/lv_draw_line.c \
Core/Lib/LVGL/src/draw/lv_draw_mask.c \
Core/Lib/LVGL/src/draw/lv_draw_rect.c \
Core/Lib/LVGL/src/draw/lv_draw_triangle.c \
Core/Lib/LVGL/src/draw/lv_draw_vector.c \
Core/Lib/LVGL/src/draw/lv_image_decoder.c \
Core/Lib/LVGL/src/draw/nxp/pxp/lv_draw_buf_pxp.c \
Core/Lib/LVGL/src/draw/nxp/pxp/lv_draw_pxp.c \
Core/Lib/LVGL/src/draw/nxp/pxp/lv_draw_pxp_fill.c \
Core/Lib/LVGL/src/draw/nxp/pxp/lv_draw_pxp_img.c \
Core/Lib/LVGL/src/draw/nxp/pxp/lv_draw_pxp_layer.c \
Core/Lib/LVGL/src/draw/nxp/pxp/lv_pxp_cfg.c \
Core/Lib/LVGL/src/draw/nxp/pxp/lv_pxp_osa.c \
Core/Lib/LVGL/src/draw/nxp/pxp/lv_pxp_utils.c \
Core/Lib/LVGL/src/draw/nxp/vglite/lv_draw_buf_vglite.c \
Core/Lib/LVGL/src/draw/nxp/vglite/lv_draw_vglite.c \
Core/Lib/LVGL/src/draw/nxp/vglite/lv_draw_vglite_arc.c \
Core/Lib/LVGL/src/draw/nxp/vglite/lv_draw_vglite_border.c \
Core/Lib/LVGL/src/draw/nxp/vglite/lv_draw_vglite_fill.c \
Core/Lib/LVGL/src/draw/nxp/vglite/lv_draw_vglite_img.c \
Core/Lib/LVGL/src/draw/nxp/vglite/lv_draw_vglite_label.c \
Core/Lib/LVGL/src/draw/nxp/vglite/lv_draw_vglite_layer.c \
Core/Lib/LVGL/src/draw/nxp/vglite/lv_draw_vglite_line.c \
Core/Lib/LVGL/src/draw/nxp/vglite/lv_draw_vglite_triangle.c \
Core/Lib/LVGL/src/draw/nxp/vglite/lv_vglite_buf.c \
Core/Lib/LVGL/src/draw/nxp/vglite/lv_vglite_matrix.c \
Core/Lib/LVGL/src/draw/nxp/vglite/lv_vglite_path.c \
Core/Lib/LVGL/src/draw/nxp/vglite/lv_vglite_utils.c \
Core/Lib/LVGL/src/draw/renesas/dave2d/lv_draw_dave2d.c \
Core/Lib/LVGL/src/draw/renesas/dave2d/lv_draw_dave2d_arc.c \
Core/Lib/LVGL/src/draw/renesas/dave2d/lv_draw_dave2d_border.c \
Core/Lib/LVGL/src/draw/renesas/dave2d/lv_draw_dave2d_fill.c \
Core/Lib/LVGL/src/draw/renesas/dave2d/lv_draw_dave2d_image.c \
Core/Lib/LVGL/src/draw/renesas/dave2d/lv_draw_dave2d_label.c \
Core/Lib/LVGL/src/draw/renesas/dave2d/lv_draw_dave2d_line.c \
Core/Lib/LVGL/src/draw/renesas/dave2d/lv_draw_dave2d_mask_rectangle.c \
Core/Lib/LVGL/src/draw/renesas/dave2d/lv_draw_dave2d_triangle.c \
Core/Lib/LVGL/src/draw/renesas/dave2d/lv_draw_dave2d_utils.c \
Core/Lib/LVGL/src/draw/sdl/lv_draw_sdl.c \
Core/Lib/LVGL/src/draw/sw/blend/lv_draw_sw_blend.c \
Core/Lib/LVGL/src/draw/sw/blend/lv_draw_sw_blend_to_argb8888.c \
Core/Lib/LVGL/src/draw/sw/blend/lv_draw_sw_blend_to_rgb565.c \
Core/Lib/LVGL/src/draw/sw/blend/lv_draw_sw_blend_to_rgb888.c \
Core/Lib/LVGL/src/draw/sw/lv_draw_sw.c \
Core/Lib/LVGL/src/draw/sw/lv_draw_sw_arc.c \
Core/Lib/LVGL/src/draw/sw/lv_draw_sw_border.c \
Core/Lib/LVGL/src/draw/sw/lv_draw_sw_box_shadow.c \
Core/Lib/LVGL/src/draw/sw/lv_draw_sw_fill.c \
Core/Lib/LVGL/src/draw/sw/lv_draw_sw_gradient.c \
Core/Lib/LVGL/src/draw/sw/lv_draw_sw_img.c \
Core/Lib/LVGL/src/draw/sw/lv_draw_sw_letter.c \
Core/Lib/LVGL/src/draw/sw/lv_draw_sw_line.c \
Core/Lib/LVGL/src/draw/sw/lv_draw_sw_mask.c \
Core/Lib/LVGL/src/draw/sw/lv_draw_sw_mask_rect.c \
Core/Lib/LVGL/src/draw/sw/lv_draw_sw_transform.c \
Core/Lib/LVGL/src/draw/sw/lv_draw_sw_triangle.c \
Core/Lib/LVGL/src/draw/sw/lv_draw_sw_vector.c \
Core/Lib/LVGL/src/draw/vg_lite/lv_draw_buf_vg_lite.c \
Core/Lib/LVGL/src/draw/vg_lite/lv_draw_vg_lite.c \
Core/Lib/LVGL/src/draw/vg_lite/lv_draw_vg_lite_arc.c \
Core/Lib/LVGL/src/draw/vg_lite/lv_draw_vg_lite_border.c \
Core/Lib/LVGL/src/draw/vg_lite/lv_draw_vg_lite_box_shadow.c \
Core/Lib/LVGL/src/draw/vg_lite/lv_draw_vg_lite_fill.c \
Core/Lib/LVGL/src/draw/vg_lite/lv_draw_vg_lite_img.c \
Core/Lib/LVGL/src/draw/vg_lite/lv_draw_vg_lite_label.c \
Core/Lib/LVGL/src/draw/vg_lite/lv_draw_vg_lite_layer.c \
Core/Lib/LVGL/src/draw/vg_lite/lv_draw_vg_lite_line.c \
Core/Lib/LVGL/src/draw/vg_lite/lv_draw_vg_lite_mask_rect.c \
Core/Lib/LVGL/src/draw/vg_lite/lv_draw_vg_lite_triangle.c \
Core/Lib/LVGL/src/draw/vg_lite/lv_draw_vg_lite_vector.c \
Core/Lib/LVGL/src/draw/vg_lite/lv_vg_lite_decoder.c \
Core/Lib/LVGL/src/draw/vg_lite/lv_vg_lite_grad.c \
Core/Lib/LVGL/src/draw/vg_lite/lv_vg_lite_math.c \
Core/Lib/LVGL/src/draw/vg_lite/lv_vg_lite_path.c \
Core/Lib/LVGL/src/draw/vg_lite/lv_vg_lite_utils.c \
Core/Lib/LVGL/src/drivers/display/drm/lv_linux_drm.c \
Core/Lib/LVGL/src/drivers/display/fb/lv_linux_fbdev.c \
Core/Lib/LVGL/src/drivers/display/ili9341/lv_ili9341.c \
Core/Lib/LVGL/src/drivers/display/lcd/lv_lcd_generic_mipi.c \
Core/Lib/LVGL/src/drivers/display/st7735/lv_st7735.c \
Core/Lib/LVGL/src/drivers/display/st7789/lv_st7789.c \
Core/Lib/LVGL/src/drivers/display/st7796/lv_st7796.c \
Core/Lib/LVGL/src/drivers/evdev/lv_evdev.c \
Core/Lib/LVGL/src/drivers/libinput/lv_libinput.c \
Core/Lib/LVGL/src/drivers/libinput/lv_xkb.c \
Core/Lib/LVGL/src/drivers/nuttx/lv_nuttx_cache.c \
Core/Lib/LVGL/src/drivers/nuttx/lv_nuttx_entry.c \
Core/Lib/LVGL/src/drivers/nuttx/lv_nuttx_fbdev.c \
Core/Lib/LVGL/src/drivers/nuttx/lv_nuttx_image_cache.c \
Core/Lib/LVGL/src/drivers/nuttx/lv_nuttx_lcd.c \
Core/Lib/LVGL/src/drivers/nuttx/lv_nuttx_libuv.c \
Core/Lib/LVGL/src/drivers/nuttx/lv_nuttx_profiler.c \
Core/Lib/LVGL/src/drivers/nuttx/lv_nuttx_touchscreen.c \
Core/Lib/LVGL/src/drivers/sdl/lv_sdl_keyboard.c \
Core/Lib/LVGL/src/drivers/sdl/lv_sdl_mouse.c \
Core/Lib/LVGL/src/drivers/sdl/lv_sdl_mousewheel.c \
Core/Lib/LVGL/src/drivers/sdl/lv_sdl_window.c \
Core/Lib/LVGL/src/drivers/windows/lv_windows_context.c \
Core/Lib/LVGL/src/drivers/windows/lv_windows_display.c \
Core/Lib/LVGL/src/drivers/windows/lv_windows_input.c \
Core/Lib/LVGL/src/drivers/x11/lv_x11_display.c \
Core/Lib/LVGL/src/drivers/x11/lv_x11_input.c \
Core/Lib/LVGL/src/font/lv_binfont_loader.c \
Core/Lib/LVGL/src/font/lv_font.c \
Core/Lib/LVGL/src/font/lv_font_dejavu_16_persian_hebrew.c \
Core/Lib/LVGL/src/font/lv_font_fmt_txt.c \
Core/Lib/LVGL/src/font/lv_font_montserrat_10.c \
Core/Lib/LVGL/src/font/lv_font_montserrat_12.c \
Core/Lib/LVGL/src/font/lv_font_montserrat_14.c \
Core/Lib/LVGL/src/font/lv_font_montserrat_16.c \
Core/Lib/LVGL/src/font/lv_font_montserrat_18.c \
Core/Lib/LVGL/src/font/lv_font_montserrat_20.c \
Core/Lib/LVGL/src/font/lv_font_montserrat_22.c \
Core/Lib/LVGL/src/font/lv_font_montserrat_24.c \
Core/Lib/LVGL/src/font/lv_font_montserrat_26.c \
Core/Lib/LVGL/src/font/lv_font_montserrat_28.c \
Core/Lib/LVGL/src/font/lv_font_montserrat_28_compressed.c \
Core/Lib/LVGL/src/font/lv_font_montserrat_30.c \
Core/Lib/LVGL/src/font/lv_font_montserrat_32.c \
Core/Lib/LVGL/src/font/lv_font_montserrat_34.c \
Core/Lib/LVGL/src/font/lv_font_montserrat_36.c \
Core/Lib/LVGL/src/font/lv_font_montserrat_38.c \
Core/Lib/LVGL/src/font/lv_font_montserrat_40.c \
Core/Lib/LVGL/src/font/lv_font_montserrat_42.c \
Core/Lib/LVGL/src/font/lv_font_montserrat_44.c \
Core/Lib/LVGL/src/font/lv_font_montserrat_46.c \
Core/Lib/LVGL/src/font/lv_font_montserrat_48.c \
Core/Lib/LVGL/src/font/lv_font_montserrat_8.c \
Core/Lib/LVGL/src/font/lv_font_simsun_16_cjk.c \
Core/Lib/LVGL/src/font/lv_font_unscii_16.c \
Core/Lib/LVGL/src/font/lv_font_unscii_8.c \
Core/Lib/LVGL/src/indev/lv_indev.c \
Core/Lib/LVGL/src/indev/lv_indev_scroll.c \
Core/Lib/LVGL/src/layouts/flex/lv_flex.c \
Core/Lib/LVGL/src/layouts/grid/lv_grid.c \
Core/Lib/LVGL/src/layouts/lv_layout.c \
Core/Lib/LVGL/src/libs/barcode/code128.c \
Core/Lib/LVGL/src/libs/barcode/lv_barcode.c \
Core/Lib/LVGL/src/libs/bin_decoder/lv_bin_decoder.c \
Core/Lib/LVGL/src/libs/bmp/lv_bmp.c \
Core/Lib/LVGL/src/libs/ffmpeg/lv_ffmpeg.c \
Core/Lib/LVGL/src/libs/freetype/lv_freetype.c \
Core/Lib/LVGL/src/libs/freetype/lv_freetype_glyph.c \
Core/Lib/LVGL/src/libs/freetype/lv_freetype_image.c \
Core/Lib/LVGL/src/libs/freetype/lv_freetype_outline.c \
Core/Lib/LVGL/src/libs/freetype/lv_ftsystem.c \
Core/Lib/LVGL/src/libs/fsdrv/lv_fs_cbfs.c \
Core/Lib/LVGL/src/libs/fsdrv/lv_fs_fatfs.c \
Core/Lib/LVGL/src/libs/fsdrv/lv_fs_littlefs.c \
Core/Lib/LVGL/src/libs/fsdrv/lv_fs_memfs.c \
Core/Lib/LVGL/src/libs/fsdrv/lv_fs_posix.c \
Core/Lib/LVGL/src/libs/fsdrv/lv_fs_stdio.c \
Core/Lib/LVGL/src/libs/fsdrv/lv_fs_win32.c \
Core/Lib/LVGL/src/libs/gif/gifdec.c \
Core/Lib/LVGL/src/libs/gif/lv_gif.c \
Core/Lib/LVGL/src/libs/libjpeg_turbo/lv_libjpeg_turbo.c \
Core/Lib/LVGL/src/libs/libpng/lv_libpng.c \
Core/Lib/LVGL/src/libs/lodepng/lodepng.c \
Core/Lib/LVGL/src/libs/lodepng/lv_lodepng.c \
Core/Lib/LVGL/src/libs/lz4/lz4.c \
Core/Lib/LVGL/src/libs/qrcode/lv_qrcode.c \
Core/Lib/LVGL/src/libs/qrcode/qrcodegen.c \
Core/Lib/LVGL/src/libs/rle/lv_rle.c \
Core/Lib/LVGL/src/libs/rlottie/lv_rlottie.c \
Core/Lib/LVGL/src/libs/tiny_ttf/lv_tiny_ttf.c \
Core/Lib/LVGL/src/libs/tjpgd/lv_tjpgd.c \
Core/Lib/LVGL/src/libs/tjpgd/tjpgd.c \
Core/Lib/LVGL/src/lv_init.c \
Core/Lib/LVGL/src/misc/cache/_lv_cache_lru_rb.c \
Core/Lib/LVGL/src/misc/cache/lv_cache.c \
Core/Lib/LVGL/src/misc/cache/lv_cache_entry.c \
Core/Lib/LVGL/src/misc/cache/lv_image_cache.c \
Core/Lib/LVGL/src/misc/lv_anim.c \
Core/Lib/LVGL/src/misc/lv_anim_timeline.c \
Core/Lib/LVGL/src/misc/lv_area.c \
Core/Lib/LVGL/src/misc/lv_array.c \
Core/Lib/LVGL/src/misc/lv_async.c \
Core/Lib/LVGL/src/misc/lv_bidi.c \
Core/Lib/LVGL/src/misc/lv_color.c \
Core/Lib/LVGL/src/misc/lv_color_op.c \
Core/Lib/LVGL/src/misc/lv_event.c \
Core/Lib/LVGL/src/misc/lv_fs.c \
Core/Lib/LVGL/src/misc/lv_ll.c \
Core/Lib/LVGL/src/misc/lv_log.c \
Core/Lib/LVGL/src/misc/lv_lru.c \
Core/Lib/LVGL/src/misc/lv_math.c \
Core/Lib/LVGL/src/misc/lv_palette.c \
Core/Lib/LVGL/src/misc/lv_profiler_builtin.c \
Core/Lib/LVGL/src/misc/lv_rb.c \
Core/Lib/LVGL/src/misc/lv_style.c \
Core/Lib/LVGL/src/misc/lv_style_gen.c \
Core/Lib/LVGL/src/misc/lv_templ.c \
Core/Lib/LVGL/src/misc/lv_text.c \
Core/Lib/LVGL/src/misc/lv_text_ap.c \
Core/Lib/LVGL/src/misc/lv_timer.c \
Core/Lib/LVGL/src/misc/lv_utils.c \
Core/Lib/LVGL/src/osal/lv_cmsis_rtos2.c \
Core/Lib/LVGL/src/osal/lv_freertos.c \
Core/Lib/LVGL/src/osal/lv_os_none.c \
Core/Lib/LVGL/src/osal/lv_pthread.c \
Core/Lib/LVGL/src/osal/lv_rtthread.c \
Core/Lib/LVGL/src/osal/lv_windows.c \
Core/Lib/LVGL/src/others/file_explorer/lv_file_explorer.c \
Core/Lib/LVGL/src/others/fragment/lv_fragment.c \
Core/Lib/LVGL/src/others/fragment/lv_fragment_manager.c \
Core/Lib/LVGL/src/others/gridnav/lv_gridnav.c \
Core/Lib/LVGL/src/others/ime/lv_ime_pinyin.c \
Core/Lib/LVGL/src/others/imgfont/lv_imgfont.c \
Core/Lib/LVGL/src/others/monkey/lv_monkey.c \
Core/Lib/LVGL/src/others/observer/lv_observer.c \
Core/Lib/LVGL/src/others/snapshot/lv_snapshot.c \
Core/Lib/LVGL/src/others/sysmon/lv_sysmon.c \
Core/Lib/LVGL/src/others/vg_lite_tvg/vg_lite_matrix.c \
Core/Lib/LVGL/src/stdlib/builtin/lv_mem_core_builtin.c \
Core/Lib/LVGL/src/stdlib/builtin/lv_sprintf_builtin.c \
Core/Lib/LVGL/src/stdlib/builtin/lv_string_builtin.c \
Core/Lib/LVGL/src/stdlib/builtin/lv_tlsf.c \
Core/Lib/LVGL/src/stdlib/clib/lv_mem_core_clib.c \
Core/Lib/LVGL/src/stdlib/clib/lv_sprintf_clib.c \
Core/Lib/LVGL/src/stdlib/clib/lv_string_clib.c \
Core/Lib/LVGL/src/stdlib/lv_mem.c \
Core/Lib/LVGL/src/stdlib/micropython/lv_mem_core_micropython.c \
Core/Lib/LVGL/src/stdlib/rtthread/lv_mem_core_rtthread.c \
Core/Lib/LVGL/src/stdlib/rtthread/lv_sprintf_rtthread.c \
Core/Lib/LVGL/src/stdlib/rtthread/lv_string_rtthread.c \
Core/Lib/LVGL/src/themes/default/lv_theme_default.c \
Core/Lib/LVGL/src/themes/lv_theme.c \
Core/Lib/LVGL/src/themes/mono/lv_theme_mono.c \
Core/Lib/LVGL/src/themes/simple/lv_theme_simple.c \
Core/Lib/LVGL/src/tick/lv_tick.c \
Core/Lib/LVGL/src/widgets/animimage/lv_animimage.c \
Core/Lib/LVGL/src/widgets/arc/lv_arc.c \
Core/Lib/LVGL/src/widgets/bar/lv_bar.c \
Core/Lib/LVGL/src/widgets/button/lv_button.c \
Core/Lib/LVGL/src/widgets/buttonmatrix/lv_buttonmatrix.c \
Core/Lib/LVGL/src/widgets/calendar/lv_calendar.c \
Core/Lib/LVGL/src/widgets/calendar/lv_calendar_header_arrow.c \
Core/Lib/LVGL/src/widgets/calendar/lv_calendar_header_dropdown.c \
Core/Lib/LVGL/src/widgets/canvas/lv_canvas.c \
Core/Lib/LVGL/src/widgets/chart/lv_chart.c \
Core/Lib/LVGL/src/widgets/checkbox/lv_checkbox.c \
Core/Lib/LVGL/src/widgets/dropdown/lv_dropdown.c \
Core/Lib/LVGL/src/widgets/image/lv_image.c \
Core/Lib/LVGL/src/widgets/imagebutton/lv_imagebutton.c \
Core/Lib/LVGL/src/widgets/keyboard/lv_keyboard.c \
Core/Lib/LVGL/src/widgets/label/lv_label.c \
Core/Lib/LVGL/src/widgets/led/lv_led.c \
Core/Lib/LVGL/src/widgets/line/lv_line.c \
Core/Lib/LVGL/src/widgets/list/lv_list.c \
Core/Lib/LVGL/src/widgets/menu/lv_menu.c \
Core/Lib/LVGL/src/widgets/msgbox/lv_msgbox.c \
Core/Lib/LVGL/src/widgets/objx_templ/lv_objx_templ.c \
Core/Lib/LVGL/src/widgets/roller/lv_roller.c \
Core/Lib/LVGL/src/widgets/scale/lv_scale.c \
Core/Lib/LVGL/src/widgets/slider/lv_slider.c \
Core/Lib/LVGL/src/widgets/span/lv_span.c \
Core/Lib/LVGL/src/widgets/spinbox/lv_spinbox.c \
Core/Lib/LVGL/src/widgets/spinner/lv_spinner.c \
Core/Lib/LVGL/src/widgets/switch/lv_switch.c \
Core/Lib/LVGL/src/widgets/table/lv_table.c \
Core/Lib/LVGL/src/widgets/tabview/lv_tabview.c \
Core/Lib/LVGL/src/widgets/textarea/lv_textarea.c \
Core/Lib/LVGL/src/widgets/tileview/lv_tileview.c \
Core/Lib/LVGL/src/widgets/win/lv_win.c \
Core/Src/Components/GUI/Elements/gui_box_measurement.c \
Core/Src/Components/GUI/Elements/gui_log_modal.c \
Core/Src/Components/GUI/Screens/gui_main_screen.c \
Core/Src/Components/bike.c \
Core/Src/Components/binary.c \
Core/Src/Components/gui.c \
Core/Src/Drivers/er_tft035.c \
Core/Src/Drivers/mcp3421.c \
Core/Src/main.c \
Core/Src/stm32f4xx_hal_msp.c \
Core/Src/stm32f4xx_it.c \
Core/Src/system_stm32f4xx.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_exti.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_flash_ramfunc.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_i2c_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_pwr_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rtc.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rtc_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_sd.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_tim_ex.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_uart.c \
Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_ll_sdmmc.c \
FATFS/App/fatfs.c \
FATFS/Target/bsp_driver_sd.c \
FATFS/Target/fatfs_platform.c \
FATFS/Target/sd_diskio.c \
Middlewares/Third_Party/FatFs/src/diskio.c \
Middlewares/Third_Party/FatFs/src/ff.c \
Middlewares/Third_Party/FatFs/src/ff_gen_drv.c \
Middlewares/Third_Party/FatFs/src/option/syscall.c


CPP_SOURCES = \
Core/Lib/LVGL/src/drivers/display/tft_espi/lv_tft_espi.cpp \
Core/Lib/LVGL/src/libs/thorvg/tvgAnimation.cpp \
Core/Lib/LVGL/src/libs/thorvg/tvgBezier.cpp \
Core/Lib/LVGL/src/libs/thorvg/tvgCanvas.cpp \
Core/Lib/LVGL/src/libs/thorvg/tvgCapi.cpp \
Core/Lib/LVGL/src/libs/thorvg/tvgCompressor.cpp \
Core/Lib/LVGL/src/libs/thorvg/tvgFill.cpp \
Core/Lib/LVGL/src/libs/thorvg/tvgInitializer.cpp \
Core/Lib/LVGL/src/libs/thorvg/tvgLoader.cpp \
Core/Lib/LVGL/src/libs/thorvg/tvgMath.cpp \
Core/Lib/LVGL/src/libs/thorvg/tvgPaint.cpp \
Core/Lib/LVGL/src/libs/thorvg/tvgPicture.cpp \
Core/Lib/LVGL/src/libs/thorvg/tvgRawLoader.cpp \
Core/Lib/LVGL/src/libs/thorvg/tvgRender.cpp \
Core/Lib/LVGL/src/libs/thorvg/tvgSaver.cpp \
Core/Lib/LVGL/src/libs/thorvg/tvgScene.cpp \
Core/Lib/LVGL/src/libs/thorvg/tvgShape.cpp \
Core/Lib/LVGL/src/libs/thorvg/tvgStr.cpp \
Core/Lib/LVGL/src/libs/thorvg/tvgSvgCssStyle.cpp \
Core/Lib/LVGL/src/libs/thorvg/tvgSvgLoader.cpp \
Core/Lib/LVGL/src/libs/thorvg/tvgSvgPath.cpp \
Core/Lib/LVGL/src/libs/thorvg/tvgSvgSceneBuilder.cpp \
Core/Lib/LVGL/src/libs/thorvg/tvgSvgUtil.cpp \
Core/Lib/LVGL/src/libs/thorvg/tvgSwCanvas.cpp \
Core/Lib/LVGL/src/libs/thorvg/tvgSwFill.cpp \
Core/Lib/LVGL/src/libs/thorvg/tvgSwImage.cpp \
Core/Lib/LVGL/src/libs/thorvg/tvgSwMath.cpp \
Core/Lib/LVGL/src/libs/thorvg/tvgSwMemPool.cpp \
Core/Lib/LVGL/src/libs/thorvg/tvgSwRaster.cpp \
Core/Lib/LVGL/src/libs/thorvg/tvgSwRenderer.cpp \
Core/Lib/LVGL/src/libs/thorvg/tvgSwRle.cpp \
Core/Lib/LVGL/src/libs/thorvg/tvgSwShape.cpp \
Core/Lib/LVGL/src/libs/thorvg/tvgSwStroke.cpp \
Core/Lib/LVGL/src/libs/thorvg/tvgTaskScheduler.cpp \
Core/Lib/LVGL/src/libs/thorvg/tvgXmlParser.cpp \
Core/Lib/LVGL/src/others/vg_lite_tvg/vg_lite_tvg.cpp


# ASM sources
ASM_SOURCES =  \
startup_stm32f446xx.s



#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
POSTFIX = "
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
GCC_PATH="/Users/tom/Library/Application Support/Code/User/globalStorage/bmd.stm32-for-vscode/@xpack-dev-tools/arm-none-eabi-gcc/12.2.1-1.2.1/.content/bin
ifdef GCC_PATH
CXX = $(GCC_PATH)/$(PREFIX)g++$(POSTFIX)
CC = $(GCC_PATH)/$(PREFIX)gcc$(POSTFIX)
AS = $(GCC_PATH)/$(PREFIX)gcc$(POSTFIX) -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy$(POSTFIX)
SZ = $(GCC_PATH)/$(PREFIX)size$(POSTFIX)
else
CXX = $(PREFIX)g++
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S

#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m4

# fpu
FPU = -mfpu=fpv4-sp-d16

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DSTM32F446xx \
-DUSE_HAL_DRIVER


# CXX defines
CXX_DEFS =  \
-DSTM32F446xx \
-DUSE_HAL_DRIVER


# AS includes
AS_INCLUDES = \

# C includes
C_INCLUDES =  \
-ICore/Inc \
-ICore/Inc/Components \
-ICore/Inc/Components/GUI/Elements \
-ICore/Inc/Components/GUI/Screens \
-ICore/Inc/Drivers \
-ICore/Lib \
-ICore/Lib/LVGL \
-ICore/Lib/LVGL/src \
-ICore/Lib/LVGL/src/core \
-ICore/Lib/LVGL/src/display \
-ICore/Lib/LVGL/src/draw \
-ICore/Lib/LVGL/src/draw/nxp/pxp \
-ICore/Lib/LVGL/src/draw/nxp/vglite \
-ICore/Lib/LVGL/src/draw/renesas/dave2d \
-ICore/Lib/LVGL/src/draw/sdl \
-ICore/Lib/LVGL/src/draw/sw \
-ICore/Lib/LVGL/src/draw/sw/arm2d \
-ICore/Lib/LVGL/src/draw/sw/blend \
-ICore/Lib/LVGL/src/draw/sw/blend/arm2d \
-ICore/Lib/LVGL/src/draw/vg_lite \
-ICore/Lib/LVGL/src/drivers \
-ICore/Lib/LVGL/src/drivers/display/drm \
-ICore/Lib/LVGL/src/drivers/display/fb \
-ICore/Lib/LVGL/src/drivers/display/ili9341 \
-ICore/Lib/LVGL/src/drivers/display/lcd \
-ICore/Lib/LVGL/src/drivers/display/st7735 \
-ICore/Lib/LVGL/src/drivers/display/st7789 \
-ICore/Lib/LVGL/src/drivers/display/st7796 \
-ICore/Lib/LVGL/src/drivers/display/tft_espi \
-ICore/Lib/LVGL/src/drivers/evdev \
-ICore/Lib/LVGL/src/drivers/libinput \
-ICore/Lib/LVGL/src/drivers/nuttx \
-ICore/Lib/LVGL/src/drivers/sdl \
-ICore/Lib/LVGL/src/drivers/windows \
-ICore/Lib/LVGL/src/drivers/x11 \
-ICore/Lib/LVGL/src/font \
-ICore/Lib/LVGL/src/indev \
-ICore/Lib/LVGL/src/layouts \
-ICore/Lib/LVGL/src/layouts/flex \
-ICore/Lib/LVGL/src/layouts/grid \
-ICore/Lib/LVGL/src/libs/barcode \
-ICore/Lib/LVGL/src/libs/bin_decoder \
-ICore/Lib/LVGL/src/libs/bmp \
-ICore/Lib/LVGL/src/libs/ffmpeg \
-ICore/Lib/LVGL/src/libs/freetype \
-ICore/Lib/LVGL/src/libs/fsdrv \
-ICore/Lib/LVGL/src/libs/gif \
-ICore/Lib/LVGL/src/libs/libjpeg_turbo \
-ICore/Lib/LVGL/src/libs/libpng \
-ICore/Lib/LVGL/src/libs/lodepng \
-ICore/Lib/LVGL/src/libs/lz4 \
-ICore/Lib/LVGL/src/libs/qrcode \
-ICore/Lib/LVGL/src/libs/rle \
-ICore/Lib/LVGL/src/libs/rlottie \
-ICore/Lib/LVGL/src/libs/thorvg \
-ICore/Lib/LVGL/src/libs/tiny_ttf \
-ICore/Lib/LVGL/src/libs/tjpgd \
-ICore/Lib/LVGL/src/misc \
-ICore/Lib/LVGL/src/misc/cache \
-ICore/Lib/LVGL/src/osal \
-ICore/Lib/LVGL/src/others/file_explorer \
-ICore/Lib/LVGL/src/others/fragment \
-ICore/Lib/LVGL/src/others/gridnav \
-ICore/Lib/LVGL/src/others/ime \
-ICore/Lib/LVGL/src/others/imgfont \
-ICore/Lib/LVGL/src/others/monkey \
-ICore/Lib/LVGL/src/others/observer \
-ICore/Lib/LVGL/src/others/snapshot \
-ICore/Lib/LVGL/src/others/sysmon \
-ICore/Lib/LVGL/src/others/vg_lite_tvg \
-ICore/Lib/LVGL/src/stdlib \
-ICore/Lib/LVGL/src/stdlib/builtin \
-ICore/Lib/LVGL/src/themes \
-ICore/Lib/LVGL/src/themes/default \
-ICore/Lib/LVGL/src/themes/mono \
-ICore/Lib/LVGL/src/themes/simple \
-ICore/Lib/LVGL/src/tick \
-ICore/Lib/LVGL/src/widgets/animimage \
-ICore/Lib/LVGL/src/widgets/arc \
-ICore/Lib/LVGL/src/widgets/bar \
-ICore/Lib/LVGL/src/widgets/button \
-ICore/Lib/LVGL/src/widgets/buttonmatrix \
-ICore/Lib/LVGL/src/widgets/calendar \
-ICore/Lib/LVGL/src/widgets/canvas \
-ICore/Lib/LVGL/src/widgets/chart \
-ICore/Lib/LVGL/src/widgets/checkbox \
-ICore/Lib/LVGL/src/widgets/dropdown \
-ICore/Lib/LVGL/src/widgets/image \
-ICore/Lib/LVGL/src/widgets/imagebutton \
-ICore/Lib/LVGL/src/widgets/keyboard \
-ICore/Lib/LVGL/src/widgets/label \
-ICore/Lib/LVGL/src/widgets/led \
-ICore/Lib/LVGL/src/widgets/line \
-ICore/Lib/LVGL/src/widgets/list \
-ICore/Lib/LVGL/src/widgets/menu \
-ICore/Lib/LVGL/src/widgets/msgbox \
-ICore/Lib/LVGL/src/widgets/objx_templ \
-ICore/Lib/LVGL/src/widgets/roller \
-ICore/Lib/LVGL/src/widgets/scale \
-ICore/Lib/LVGL/src/widgets/slider \
-ICore/Lib/LVGL/src/widgets/span \
-ICore/Lib/LVGL/src/widgets/spinbox \
-ICore/Lib/LVGL/src/widgets/spinner \
-ICore/Lib/LVGL/src/widgets/switch \
-ICore/Lib/LVGL/src/widgets/table \
-ICore/Lib/LVGL/src/widgets/tabview \
-ICore/Lib/LVGL/src/widgets/textarea \
-ICore/Lib/LVGL/src/widgets/tileview \
-ICore/Lib/LVGL/src/widgets/win \
-IDrivers/CMSIS/Device/ST/STM32F4xx/Include \
-IDrivers/CMSIS/Include \
-IDrivers/STM32F4xx_HAL_Driver/Inc \
-IDrivers/STM32F4xx_HAL_Driver/Inc/Legacy \
-IFATFS/App \
-IFATFS/Target \
-IMiddlewares/Third_Party/FatFs/src



# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS = $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CXXFLAGS = $(MCU) $(CXX_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections -feliminate-unused-debug-types

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf -ggdb
CXXFLAGS += -g -gdwarf -ggdb
endif

# Add additional flags
CFLAGS += -Wall -fdata-sections -ffunction-sections 
ASFLAGS += -Wall -fdata-sections -ffunction-sections 
CXXFLAGS += 

# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"
CXXFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"

#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32F446RETx_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = \


# Additional LD Flags from config file
ADDITIONALLDFLAGS = -Wl,--print-memory-usage -specs=nano.specs 

LDFLAGS = $(MCU) $(ADDITIONALLDFLAGS) -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of cpp program objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(CPP_SOURCES:.cpp=.o)))
vpath %.cpp $(sort $(dir $(CPP_SOURCES)))

# list of C objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))

# list of ASM program objects
UPPER_CASE_ASM_SOURCES = $(filter %.S,$(ASM_SOURCES))
LOWER_CASE_ASM_SOURCES = $(filter %.s,$(ASM_SOURCES))

OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(UPPER_CASE_ASM_SOURCES:.S=.o)))
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(LOWER_CASE_ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))

$(BUILD_DIR)/%.o: %.cpp STM32Make.make | $(BUILD_DIR) 
	$(CXX) -c $(CXXFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.cpp=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.cxx STM32Make.make | $(BUILD_DIR) 
	$(CXX) -c $(CXXFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.cxx=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.c STM32Make.make | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s STM32Make.make | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/%.o: %.S STM32Make.make | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) STM32Make.make
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@

$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@

$(BUILD_DIR):
	mkdir $@

#######################################
# flash
#######################################
flash: $(BUILD_DIR)/$(TARGET).elf
	"/Users/tom/Library/Application Support/Code/User/globalStorage/bmd.stm32-for-vscode/@xpack-dev-tools/openocd/0.12.0-1.1/.content/bin/openocd" -f ./openocd.cfg -c "program $(BUILD_DIR)/$(TARGET).elf verify reset exit"

#######################################
# erase
#######################################
erase: $(BUILD_DIR)/$(TARGET).elf
	"/Users/tom/Library/Application Support/Code/User/globalStorage/bmd.stm32-for-vscode/@xpack-dev-tools/openocd/0.12.0-1.1/.content/bin/openocd" -f ./openocd.cfg -c "init; reset halt; stm32f4x mass_erase 0; exit"

#######################################
# clean up
#######################################
clean:
	-rm -fR $(BUILD_DIR)

#######################################
# custom makefile rules
#######################################


	
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***